databases:
  - name: apitasks
    databaseName: apitasks
    user: apitasks_user

services:
  - type: web
    name: app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apitasks
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4